package orchestrator

import (
	"context"
	"fmt"
	"path/filepath"
	"time"

	"github.com/tickraft/taichi/pkg/agent"
	"github.com/tickraft/taichi/pkg/failure"
	"github.com/tickraft/taichi/pkg/i18n"
	"github.com/tickraft/taichi/pkg/skill"
)

// defaultMaxRounds is the default maximum number of fix rounds in copilot mode.
const defaultMaxRounds = 3

// CopilotOptions holds the run parameters for copilot mode.
type CopilotOptions struct {
	// Options embeds the normal run options.
	Options
	// MaxRounds is the maximum number of fix rounds. 0 means use the default value 3.
	MaxRounds int
	// Invoker is the AI Agent invoker. When nil, copilot degrades to a normal Run.
	Invoker agent.Invoker
	// PatchApplier applies the patch generated by the Agent. When nil, a default applier for the project root is used.
	PatchApplier *agent.PatchApplier
}

// CopilotResult is the output of copilot mode.
type CopilotResult struct {
	// Final is the result of the final test round.
	Final Result
	// Rounds holds the details of each fix round.
	Rounds []CopilotRound
	// TotalDuration is the total time spent by copilot (including fix and regression).
	TotalDuration time.Duration
	// Fixed is true when the regression test passed after the Agent's fix.
	Fixed bool
}

// CopilotRound describes the details of a single fix round.
type CopilotRound struct {
	// Round is the round number (starting from 1).
	Round int
	// TestResult is the test result of this round.
	TestResult Result
	// FailureContext is the failure context of this round (if any failures).
	FailureContext *failure.Context
	// FixResult is the fix result returned by the Agent (if any).
	FixResult *agent.FixResult
	// ApplyError is the error encountered while applying the fix (if any).
	ApplyError error
	// AgentError is the error encountered while invoking the Agent (if any).
	AgentError error
}

// RunCopilot executes the full test→fix→regression closed loop.
//
// Flow:
//  1. Run tests (orchestrator.Run)
//  2. If all pass, return immediately
//  3. If there are failures and MaxRounds is not exceeded:
//     a. Build the failure context
//     b. Invoke the AI Agent to analyze and fix
//     c. Apply the fix (patch or direct)
//     d. Re-run tests (regression)
//     e. If regression passes, mark Fixed=true and return
//     f. If regression still has failures, increment the round and go back to step 3
//  4. If MaxRounds is exceeded while failures remain, return the last failure result
func (o *Orchestrator) RunCopilot(ctx context.Context, opts CopilotOptions) (*CopilotResult, error) {
	start := time.Now()
	logger := opts.Logger
	if logger == nil {
		logger = skill.NoOpLogger{}
	}

	maxRounds := opts.MaxRounds
	if maxRounds <= 0 {
		maxRounds = defaultMaxRounds
	}

	result := &CopilotResult{}

	// First round of tests.
	logger.Infof(i18n.T("copilot.round.initial"))
	firstResult, err := o.Run(ctx, opts.Options)
	if err != nil {
		return nil, fmt.Errorf("copilot round 1: %w", err)
	}
	result.Final = firstResult

	// If no failures, return directly.
	if firstResult.Summary.Failed == 0 {
		result.TotalDuration = time.Since(start)
		result.Fixed = true
		logger.Infof(i18n.T("copilot.round.all_passed"))
		return result, nil
	}

	// If no Invoker, degrade to a normal Run.
	if opts.Invoker == nil {
		result.TotalDuration = time.Since(start)
		logger.Warnf(i18n.T("copilot.round.no_invoker"))
		return result, nil
	}

	// Prepare patch applier.
	applier := opts.PatchApplier
	if applier == nil {
		applier = agent.NewPatchApplier(firstResult.ProjectRoot)
	}

	// Fix loop.
	for round := 1; round <= maxRounds; round++ {
		roundStart := time.Now()

		// Build the failure context.
		currentResult := result.Final
		fc := failure.FromResults(
			currentResult.ProjectName,
			currentResult.BaseURL,
			currentResult.ProjectRoot,
			currentResult.EnvLogPath,
			currentResult.ReportsDir,
			currentResult.Results,
			nil,
		)

		// Write the failure context file.
		fcPath := filepath.Join(currentResult.ReportsDir,
			fmt.Sprintf("failures-round-%d-%s.json", round, time.Now().Format("20060102-150405")))
		if err := fc.WriteToFile(fcPath); err != nil {
			logger.Warnf(i18n.T("copilot.round.write_fc_error"), err)
		} else {
			logger.Infof(i18n.T("copilot.round.fc_written"), fcPath)
		}

		copilotRound := CopilotRound{
			Round:          round,
			TestResult:     currentResult,
			FailureContext: fc,
		}

		// Invoke the AI Agent.
		logger.Infof(i18n.T("copilot.round.invoking_agent"),
			round, opts.Invoker.Name(), len(fc.FailedCases))
		fixResult, agentErr := opts.Invoker.AnalyzeAndFix(ctx, fc)
		copilotRound.FixResult = fixResult
		copilotRound.AgentError = agentErr
		if agentErr != nil {
			logger.Errorf(i18n.T("copilot.round.agent_failed"), round, agentErr)
			result.Rounds = append(result.Rounds, copilotRound)
			break
		}

		if fixResult == nil || !fixResult.Fixed {
			logger.Warnf(i18n.T("copilot.round.agent_cannot_fix"),
				round, agentFixMessage(fixResult))
			result.Rounds = append(result.Rounds, copilotRound)
			break
		}

		logger.Infof(i18n.T("copilot.round.agent_fixed"),
			round, fixResult.Mode, fixResult.Message)

		// Apply the fix.
		applyErr := applier.ApplyResult(fixResult)
		copilotRound.ApplyError = applyErr
		if applyErr != nil {
			logger.Errorf(i18n.T("copilot.round.apply_failed"), round, applyErr)
			result.Rounds = append(result.Rounds, copilotRound)
			break
		}

		logger.Infof(i18n.T("copilot.round.applied"), round)
		result.Rounds = append(result.Rounds, copilotRound)

		// Re-run tests (regression).
		logger.Infof(i18n.T("copilot.round.regression"), round+1)
		regressionResult, runErr := o.Run(ctx, opts.Options)
		if runErr != nil {
			return nil, fmt.Errorf("copilot round %d regression: %w", round+1, runErr)
		}

		result.Final = regressionResult

		if regressionResult.Summary.Failed == 0 {
			result.Fixed = true
			result.TotalDuration = time.Since(start)
			logger.Infof(i18n.T("copilot.round.regression_passed"), round)
			return result, nil
		}

		logger.Warnf(i18n.T("copilot.round.regression_remaining"),
			round+1, regressionResult.Summary.Failed)

		_ = roundStart // roundStart is only used for potential fine-grained timing in the future
	}

	result.TotalDuration = time.Since(start)
	logger.Warnf(i18n.T("copilot.round.exhausted"),
		maxRounds, result.Final.Summary.Failed)
	return result, nil
}

// agentFixMessage safely extracts the message from a FixResult.
func agentFixMessage(r *agent.FixResult) string {
	if r == nil {
		return "nil fix result"
	}
	if r.Message != "" {
		return r.Message
	}
	return "no message from agent"
}
