package agent

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// PatchApplier applies the unified diff patch generated by the AI Agent to the project source code.
//
// It prefers `git apply` (which supports precise path resolution and rollback) and falls back to the `patch` command.
// Both are invoked as subprocesses; no third-party patch library is introduced.
type PatchApplier struct {
	// ProjectRoot is the absolute path of the project root directory. Paths in the patch are resolved relative to this directory.
	ProjectRoot string
}

// NewPatchApplier creates a PatchApplier for the given project root.
func NewPatchApplier(projectRoot string) *PatchApplier {
	return &PatchApplier{ProjectRoot: projectRoot}
}

// Apply applies the unified diff patch to the workspace.
// It returns the list of files modified by the patch (parsed from the patch header).
func (pa *PatchApplier) Apply(patch string) ([]string, error) {
	if patch == "" {
		return nil, fmt.Errorf("empty patch")
	}
	if pa.ProjectRoot == "" {
		return nil, fmt.Errorf("project root not set")
	}

	files := parsePatchFiles(patch)

	// Prefer git apply.
	if err := pa.tryGitApply(patch); err == nil {
		return files, nil
	}

	// Fall back to the patch command.
	if err := pa.tryPatchCommand(patch); err == nil {
		return files, nil
	}

	return files, fmt.Errorf("both git apply and patch command failed")
}

// tryGitApply attempts to apply the patch via git apply.
func (pa *PatchApplier) tryGitApply(patch string) error {
	gitPath, err := exec.LookPath("git")
	if err != nil {
		return fmt.Errorf("git not found: %w", err)
	}

	cmd := exec.Command(gitPath, "apply", "--whitespace=fix", "-")
	cmd.Dir = pa.ProjectRoot
	cmd.Stdin = strings.NewReader(patch)

	var stderr strings.Builder
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("git apply failed: %w (stderr: %s)", err, strings.TrimSpace(stderr.String()))
	}
	return nil
}

// tryPatchCommand attempts to apply the patch via the patch command.
func (pa *PatchApplier) tryPatchCommand(patch string) error {
	patchPath, err := exec.LookPath("patch")
	if err != nil {
		return fmt.Errorf("patch command not found: %w", err)
	}

	cmd := exec.Command(patchPath, "-p1", "--no-backup-if-mismatch", "-r", "-")
	cmd.Dir = pa.ProjectRoot
	cmd.Stdin = strings.NewReader(patch)

	var stderr strings.Builder
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("patch command failed: %w (stderr: %s)", err, strings.TrimSpace(stderr.String()))
	}
	return nil
}

// VerifyDirectFix verifies that the list of files modified by the Agent actually exist and are readable.
// Used in direct mode: after the Agent modifies source files via file-editing tools, taichi verifies the modifications are valid.
func (pa *PatchApplier) VerifyDirectFix(modifiedFiles []string) error {
	if len(modifiedFiles) == 0 {
		return fmt.Errorf("no modified files to verify")
	}
	for _, f := range modifiedFiles {
		path := f
		if !filepath.IsAbs(path) {
			path = filepath.Join(pa.ProjectRoot, path)
		}
		info, err := os.Stat(path)
		if err != nil {
			return fmt.Errorf("modified file %s not accessible: %w", f, err)
		}
		if info.IsDir() {
			return fmt.Errorf("modified path %s is a directory, expected a file", f)
		}
	}
	return nil
}

// ApplyResult applies the fix in a FixResult.
// In FixModePatch mode it applies the patch; in FixModeDirect mode it verifies file existence.
func (pa *PatchApplier) ApplyResult(result *FixResult) error {
	if result == nil {
		return fmt.Errorf("nil fix result")
	}
	if !result.Fixed {
		return fmt.Errorf("fix result indicates not fixed: %s", result.Message)
	}

	switch result.Mode {
	case FixModePatch:
		if result.Patch == "" {
			return fmt.Errorf("patch mode but empty patch content")
		}
		_, err := pa.Apply(result.Patch)
		return err
	case FixModeDirect:
		return pa.VerifyDirectFix(result.ModifiedFiles)
	default:
		return fmt.Errorf("unknown fix mode: %s", result.Mode)
	}
}

// parsePatchFiles parses the modified file paths from a unified diff.
// Supports the "--- a/path" / "+++ b/path" format (git diff style).
func parsePatchFiles(patch string) []string {
	var files []string
	seen := make(map[string]struct{})

	lines := strings.Split(patch, "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "+++ ") {
			path := strings.TrimPrefix(line, "+++ ")
			// Strip the b/ prefix (git diff style).
			path = strings.TrimPrefix(path, "b/")
			// Strip the trailing timestamp (e.g. " 2024-01-01 00:00:00").
			if idx := strings.Index(path, "\t"); idx >= 0 {
				path = path[:idx]
			}
			path = strings.TrimSpace(path)
			if path == "" || path == "/dev/null" {
				continue
			}
			if _, ok := seen[path]; !ok {
				seen[path] = struct{}{}
				files = append(files, path)
			}
		}
	}
	return files
}
